name: pipeline
on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.3

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run Linting
        run: make lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      actions: none
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.3

      - name: Run Tests
        run: make test-coverage

  # TODO: add build stage + dockerhub push

  release:
    if: contains(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    permissions:
      actions: none
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
